---
- hosts: local
  gather_facts: no
  tasks:
  - debug:
      msg: Test Message
  - name: run
    shell: ls
    register: ps
  - debug: var=ps.stdout_lines
  - debug: msg="{{ lookup('pipe','date') }}"
  - debug: msg="{{ lookup('pipe', 'python3 run.py')}}"
